#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

usage () { echo "usage: `basename $0` chrootdir" ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

[ $# -eq 1 ] || usageerr

DI="$1"

# clean up any old chroot
[ ! -d "$DI/proc" ] || sudo umount "$DI"/proc || true
[ ! -d "$DI/sys" ] || sudo umount "$DI"/sys || true
[ ! -d "$DI" ] || sudo rm -rf "$DI"

sudo debootstrap --include=locales,dh-di,less,git,subversion,mr,vim-nox,udev,autoconf,automake,uuid-dev,zlib1g-dev,debian-keyring,aptitude,dialog,procps,kernel-wedge,xmlto,devscripts \
	--unpack-tarball=`pwd`/packages.tgz --variant=buildd unstable "$DI"
sudo chroot "$DI" dpkg-reconfigure locales
sudo chroot "$DI" mount -t proc procfs /proc
echo "deb-src http://ftp.us.debian.org/debian/ unstable main non-free contrib" | \
	sudo tee -a "$DI/etc/apt/sources.list"
sudo chroot "$DI" apt-get -y update
sudo chroot "$DI" apt-get -y build-dep debian-installer
sudo chroot "$DI" svn co svn://svn.debian.org/svn/d-i
sudo chroot "$DI" cd /d-i && scripts/git-setup && mr -p checkout
sudo cp local "$DI/d-i/installer/build/pkg-lists/"
# Apply patch to d-i
sudo chroot "$DI" umount /proc
sudo chown -R $USERNAME:$USERNAME "$DI"
sudo chroot "$DI" mount -t proc procfs /proc
sudo chroot "$DI" mount -t sysfs sysfs /sys
cp -r spl* zfs* "$DI"
echo "Now type 'sudo chroot \"$DI\" /innerbuild' to perform inner building..."
