#!/usr/bin/env bash

# This exists only to update the packages.tgz file used by debootstrap to
# create the chroot. To update the submodules, run make with the 'subupdate'
# target.

set -e
set -o nounset
set -o pipefail

usage () { echo "usage: `basename $0` filename" ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

[ $# -eq 1 ] || usageerr

debootstrap --make-tarball="$1" \
	--include=locales,dh-di,less,git,mr,vim-nox,\
udev,autoconf,uuid-dev,zlib1g-dev,debian-keyring,aptitude,dialog,\
procps,devscripts,ca-certificates,fakeroot,\
libdebconfclient0-dev,libdebian-installer4-dev,libtool,\
libncursesw5-dev,libklibc-dev,autoconf-archive,makedev,\
gnupg-agent,pinentry-curses,gawk,grub-efi-amd64-bin,xorriso,\
libwww-perl,libcrypt-ssleay-perl \
	--variant=buildd unstable dibuild
