#!/usr/bin/env bash

# This exists only to update the packages.tgz file used by debootstrap to
# create the chroot. To update the submodules, run make with the 'subupdate'
# target.

set -e
set -o nounset
set -o pipefail

usage () { echo "usage: `basename $0` filename" ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

[ $# -eq 1 ] || usageerr

sudo debootstrap --include=locales,dh-di,less,git,subversion,mr,rsync,vim-nox,udev,autoconf,uuid-dev,zlib1g-dev,debian-keyring,aptitude,dialog,procps,xmlto,kernel-wedge,openssh-client,devscripts,ca-certificates,fakeroot,libdebconfclient0-dev,libdebian-installer4-dev,libtool \
	--make-tarball="$1" --variant=buildd unstable dibuild
