#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

usage () { echo "usage: `basename $0`" ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

[ $# -eq 0 ] || usageerr

sudo debootstrap --include=locales,dh-di,vim-tiny,udev,autoconf,uuid-dev,zlib1g-dev,debian-keyring,aptitude,dialog,procps,xmlto,kernel-wedge,devscripts \
	--make-tarball=`pwd`/packages.tgz --variant=buildd unstable dibuild
