Document: spl-modules-3.3.3-1-amd64-di
Title: Debian spl-modules-3.3.3-1-amd64-di Manual
Author: <insert document author here>
Abstract: This manual describes what spl-modules-3.3.3-1-amd64-di is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spl-modules-3.3.3-1-amd64-di/spl-modules-3.3.3-1-amd64-di.sgml.gz

Format: postscript
Files: /usr/share/doc/spl-modules-3.3.3-1-amd64-di/spl-modules-3.3.3-1-amd64-di.ps.gz

Format: text
Files: /usr/share/doc/spl-modules-3.3.3-1-amd64-di/spl-modules-3.3.3-1-amd64-di.text.gz

Format: HTML
Index: /usr/share/doc/spl-modules-3.3.3-1-amd64-di/html/index.html
Files: /usr/share/doc/spl-modules-3.3.3-1-amd64-di/html/*.html
