#!/bin/sh

set -- $1

fs=$1
mp=$2
type=$3
options=$4
dump=$5
pass=$6

#FIXME
case $type in
    zfs)
	zfs mount ${options:+-o "$options"} $fs /target$mp || exit 1
	echo "zfs unmount /target$mp"
	exit 0
	;;
esac

exit 1
