Document: spl
Title: Debian spl Manual
Author: <insert document author here>
Abstract: This manual describes what spl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spl/spl.sgml.gz

Format: postscript
Files: /usr/share/doc/spl/spl.ps.gz

Format: text
Files: /usr/share/doc/spl/spl.text.gz

Format: HTML
Index: /usr/share/doc/spl/html/index.html
Files: /usr/share/doc/spl/html/*.html
