#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = zfs ]; then
		>/var/lib/partman/zfs
	fi
done

if ! [ -f /var/lib/partman/zfs ] && \
   modprobe zfs >/dev/null 2>/dev/null; then
	>/var/lib/partman/zfs
fi

if ! [ -f /var/lib/partman/zfs ] && \
   grep -q zfs /proc/filesystems; then
	>/var/lib/partman/zfs
fi
