Document: partman-zfs
Title: Debian partman-zfs Manual
Author: <insert document author here>
Abstract: This manual describes what partman-zfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/partman-zfs/partman-zfs.sgml.gz

Format: postscript
Files: /usr/share/doc/partman-zfs/partman-zfs.ps.gz

Format: text
Files: /usr/share/doc/partman-zfs/partman-zfs.text.gz

Format: HTML
Index: /usr/share/doc/partman-zfs/html/index.html
Files: /usr/share/doc/partman-zfs/html/*.html
