#!/bin/sh
# Scan a whole tree for translations.
set -e
for dir in $(find $1 -type d | grep /debian\$ | grep -v svn | sort); do
	if [ -e "$dir/control" ] &&
	   ( [ -e "$dir/po" ] || [ -e "$dir/../po" ] || [ -n "$(ls $dir/../*/po -d 2>/dev/null)" ] )
   	then
		base=$(echo $dir | sed 's/\/debian$//');
		if head -n 1 $dir/changelog | grep -q UNRELEASED; then
			unreleased=true

			if [ "$2" = "l10n-only" ]; then
				continue
			fi
		else
			unreleased=false

			if [ "$2" = "unreleased-only" ]; then
				continue
			fi
		fi
		if SCAN_TRANS=1 `dirname $0`/output-l10n-changes -d $base; then
			if [ "$unreleased" = "true" ]; then
				echo "   (Plus other UNRELEASED changes.)"
			fi
			echo ""
		fi
	fi
done
echo ""
printf "Generated "
date -R
